classdef cyclic5 < OpenSees
   
    properties
        
        format = ' %0.12f';
        
        ctrlNode    % control node
        ctrldof     % control dof
        targetDisp  % array of displacement targets
        targetIncr  % target displacement increment (absolute)
        tol         % convergence tolerance
        maxIter     % maximum number of iterations for convergence
                
    end
    
    methods
        
        function obj = cyclic5(ctrlNode,ctrldof,targetDisp,targetIncr,tol,maxIter)
           
            % store variables
            obj.ctrlNode = ctrlNode;
            obj.ctrldof = ctrldof;
            obj.targetDisp = targetDisp;
            obj.targetIncr = targetIncr;
            obj.tol = tol;
            obj.maxIter = maxIter;
                       
            % analysis convergence loop
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'set ctrlNode ' num2str(obj.ctrlNode.tag) ';\n' ...
                           'set ctrlDOF ' num2str(obj.ctrldof) ';\n' ...
                           'set targIncr ' num2str(obj.targetIncr) ';\n' ...
                           'set targTol ' num2str(obj.tol,obj.format) ';\n' ...
                           'set maxIter ' num2str(obj.maxIter) ';\n' ...
                           'foreach targDisp {' num2str(obj.targetDisp) '} {\n' ...
                           '\t'     'constraints Plain;\n' ...
                           '\t'     'numberer RCM;\n' ...
                           '\t'     'system Umfpack;\n' ...
                           '\t'     'set ctrlDisp [nodeDisp $ctrlNode $ctrlDOF];\n' ...
                           '\t'     'set travel 0.0;\n' ...
                           '\t'     'set relDisp [expr $targDisp - $ctrlDisp];\n' ...
                           '\t'     'if {$relDisp > 0} {\n' ...
                           '\t\t'       'set sgn 1.0;\n' ...
                           '\t'     '} else {\n' ...
                           '\t\t'       'set sgn -1.0;\n' ...
                           '\t'     '};\n' ...
                           '\t'     'set incr [expr $sgn*$targIncr];\n' ...
                           '\t'     'puts "\n> excursion: $targDisp | increment: $incr\n";\n' ...
                           '\t'     'while {[expr abs($travel)] < [expr abs($relDisp)]} {\n' ...
                           '\t\t'       'test NormDispIncr $targTol $maxIter;\n' ...
                           '\t\t'       'algorithm Newton;\n' ...
                           '\t\t'       'integrator DisplacementControl $ctrlNode $ctrlDOF $incr;\n' ...
                           '\t\t'       'analysis Static;\n' ...
                           '\t\t'       'set ok [analyze 1];\n' ...
                           '\t\t'       'if {$ok == 0} {\n' ...
                           '\t\t\t'         'set travel [expr $travel + $incr];\n' ...
                           '\t\t'       '} elseif {$ok != 0} {\n' ...
                           '\t\t\t'         'set prntDisp [expr int([nodeDisp $ctrlNode $ctrlDOF]*100.0)/100.0];\n' ...
                           '\t\t\t'         'puts "\t> at $prntDisp";\n' ...
                           '\t\t\t'         'set tempIncr $incr;\n' ...
                           '\t\t\t'         'set denom 2.0;\n' ...
                           '\t\t\t'         'set counter 0;\n' ...
                           '\t\t\t'         'set tempTol $targTol;\n' ...
                           '\t\t\t'         'while {$ok != 0} {\n' ...
                           '\t\t\t\t'           'incr counter;\n' ...
                           '\t\t\t\t'           'if {$counter == 1} {\n' ...
                           '\t\t\t\t\t'             'algorithm KrylovNewton -maxDim 6;\n' ...
                           '\t\t\t\t'           '} elseif {$counter == 8} {\n' ...
                           '\t\t\t\t\t'             'test NormDispIncr [expr $targTol*10.0] $maxIter;\n' ...
                           '\t\t\t\t'           '} elseif {$counter == 16} {\n' ...
                           '\t\t\t\t\t'             'exit;\n' ...
                           '\t\t\t\t'           '};\n' ...
                           '\t\t\t\t'           'set tempIncr [expr $tempIncr/$denom];\n' ...
                           '\t\t\t\t'           'puts "\t\t> trying increment: $tempIncr";\n' ...
                           '\t\t\t\t'           'integrator DisplacementControl $ctrlNode $ctrlDOF $tempIncr;\n' ...
                           '\t\t\t\t'           'set ok [analyze 1];\n' ...
                           '\t\t\t'         '};\n' ...
                           '\t\t\t'         'set travel [expr $travel + $tempIncr];\n' ...
                           '\t\t'       '};\n' ...
                           '\t'     '};\n' ...
                           '}'];
                       
        end
        
    end
    
end