classdef eigen_analysis < OpenSees
    
    properties
        
        n_eigen     % number of eigenvalues required
        file_name   % file name for eigenvalue output
        
    end
    
    methods
   
        function obj = eigen_analysis(n_eigen, file_name)
            
            obj.n_eigen = n_eigen;            
            obj.file_name = file_name;
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'set file_name "' obj.file_name '";\n' ...
                           'set file_ID [open $file_name "w"];\n' ...
                           'set eigenvalues [eigen ' num2str(obj.n_eigen) '];\n' ...
                           'puts $file_ID $eigenvalues;\n' ...
                           'close $file_ID;\n' ...
                           'set file_name "' obj.file_name '.mass";\n' ...
                           'set file_ID [open $file_name "w"];\n' ...
                           'foreach node_tag [getNodeTags] {\n' ...
                           '\t'     'set node_mass [nodeMass $node_tag 1];\n' ...
                           '\t'     'puts $file_ID "$node_tag,$node_mass";\n' ...
                           '};\n' ...
                           'close $file_ID;\n' ...
                           'record'];
                           
            
        end
        
    end
    
end