classdef gravity2 < OpenSees
    
    properties
        
    end
    
    methods
   
        function obj = gravity2(num_steps)
           
            obj.cmdLine = ['\n' ...
                           'constraints Transformation;\n' ...
                           'numberer RCM;\n' ...
                           'system BandGeneral;\n' ...
                           'test NormDispIncr 1.0e-6 100;\n' ...
                           'algorithm Newton;\n' ...
                           'integrator LoadControl 0.1;\n' ...
                           'analysis Static;\n' ...
                           'analyze ' num2str(num_steps) ';\n' ...
                           'loadConst -time 0.0;\n' ...
                           'wipeAnalysis'];
            
        end
        
    end
    
end