classdef gravity3 < OpenSees
    
    properties
        
    end
    
    methods
   
        function obj = gravity3()
           
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'constraints Plain;\n' ...
                           'numberer RCM;\n' ...
                           'system Mumps;\n' ...
                           'test NormDispIncr 1.0e-8 100;\n' ...
                           'algorithm Newton;\n' ...
                           'integrator LoadControl 0.1;\n' ...
                           'analysis Static;\n' ...
                           'analyze 10;\n' ...
                           'loadConst -time 0.0;\n' ...
                           'puts "\n> gravity load applied";\n' ...
                           'wipeAnalysis'];
            
        end
        
    end
    
end