classdef gravity1 < OpenSees
    
    properties
        
    end
    
    methods
   
        function obj = gravity1()
           
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'constraints Transformation;\n' ...
                           'numberer RCM;\n' ...
                           'system BandGeneral;\n' ...
                           'test NormDispIncr 1.0e-6 1000;\n' ...
                           'algorithm Newton;\n' ...
                           'integrator LoadControl [expr 1/20];\n' ...
                           'analysis Static;\n' ...
                           'analyze 20;\n' ...
                           'loadConst -time 0.0;\n' ...
                           'wipeAnalysis'];
            
        end
        
    end
    
end