classdef input_accelerogram2 < OpenSees
    
    properties

        format = ' %0.9f';
        
        gm          % ground motion metadata and time history (input accelerogram)
        g           % gravitational acceleration
        dof         % degree of freedom of acceleration
        dt          % analysis time step
        free_time   % duration of free vibration after ground motion
        tol         % convergence tolerance
        max_iter    % maximum number of interations for convergence
        zeta        % damping ratio
        eigen_file  % file with list of eigenvalues
        
    end
    
    methods
        
        function obj = input_accelerogram2(gm, g, dof, dt, free_time, tol, max_iter, zeta, eigen_file)
            
            % store variables
            obj.gm = gm;
            obj.g = g;
            obj.dof = dof;
            obj.dt = dt;
            obj.free_time = free_time;
            obj.tol = tol;
            obj.max_iter = max_iter;
            obj.zeta = zeta;
            obj.eigen_file = eigen_file;
            
            history_appended = vertcat(obj.gm.history*g, zeros(obj.free_time/obj.gm.dt, 1)).';
            n_total_steps = ceil(length(history_appended)*obj.gm.dt/obj.dt);
            
            % read file with eigenvalues
            eig = load(obj.eigen_file);
            omega = sqrt(eig);
            T = 2*pi./omega;
            beta = 2*zeta/(omega(1) + omega(2));
            alpha = omega(1)*omega(2)*beta;
            
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'rayleigh ' num2str(alpha, obj.format) ' ' num2str(beta, obj.format) ' 0.0 0.0;\n' ...
                           'set ts_tag 2;\n' ...
                           'timeSeries Path $ts_tag -dt ' num2str(obj.gm.dt, obj.format) ' -values {' num2str(history_appended, obj.format) '} -prependZero;\n' ...
                           'pattern UniformExcitation 1 ' num2str(obj.dof) ' -accel $ts_tag\n' ...
                           'constraints Plain;\n' ...
                           'numberer RCM;\n' ...
                           'system Mumps -ICNTL 80;\n' ...
                           'test NormDispIncr ' num2str(obj.tol, obj.format) ' ' num2str(obj.max_iter) ';\n' ...
                           'set dt ' num2str(obj.dt, obj.format) ';\n' ...
                           'set n_steps ' num2str(n_total_steps) ';\n' ...
                           'set cur_step 1;\n' ...
                           'while {$cur_step < $n_steps} {\n' ...
                           '\t'     'set counter 0;\n' ...
                           '\t'     'algorithm Newton;\n' ...
                           '\t'     'integrator Newmark 0.5 0.25;\n' ...
                           '\t'     'analysis Transient;\n' ...
                           '\t'     'set ok [analyze 1 $dt];\n' ...
                           '\t'     'if {$ok != 0} {\n' ...
                           '\t\t'       'puts "\n\t> analysis failed to converge at step $cur_step";\n' ...
                           '\t\t'       'puts "\t\t> trying KrylovNewton";\n' ...
                           '\t\t'       'set time_travel 0.0;\n' ...
                           '\t\t'       'while {$time_travel < $dt} {\n' ...
                           '\t\t\t'         'set counter 0;\n' ...
                           '\t\t\t'         'set diff [expr $dt - $time_travel];\n' ...
                           '\t\t\t'         'set ok [analyze 1 $diff];\n' ...
                           '\t\t\t'         'if {$ok != 0} {\n' ...
                           '\t\t\t\t'           'incr counter;\n' ...
                           '\t\t\t\t'           'while {$ok != 0} {\n' ...
                           '\t\t\t\t\t'             'if {$counter > 5} {\n' ...
                           '\t\t\t\t\t\t'               'exit;\n' ...
                           '\t\t\t\t\t'             '};\n' ...
                           '\t\t\t\t\t'             'set diff [expr $diff/10.0];\n' ...
                           '\t\t\t\t\t'             'puts "\t\t> trying dt = $diff";\n' ...
                           '\t\t\t\t\t'             'set ok [analyze 1 $diff];\n' ...
                           '\t\t\t\t\t'             'incr counter;\n' ...
                           '\t\t\t\t'           '};\n' ...
                           '\t\t\t'         '};\n' ...
                           '\t\t\t'         'set time_travel [expr $time_travel + $diff];\n' ...
                           '\t\t'       '};\n' ...
                           '\t'     '};\n' ...
                           '\t'     'incr cur_step;\n' ...
                           '\t'     'if {$cur_step%%100 == 0} {\n' ...
                           '\t\t'       'puts "> step $cur_step complete";\n' ...
                           '\t'     '};\n' ...
                           '}'];
            
        end
        
    end
    
end
