classdef static1 < OpenSees
    
    properties
        
    end
    
    methods
   
        function obj = static1()
           
            obj.cmdLine = [obj.cmdLine '\n' ...
                           'constraints Transformation;\n' ...
                           'numberer RCM;\n' ...
                           'system BandGeneral;\n' ...
                           'test NormDispIncr 1.0e-6 1000;\n' ...
                           'algorithm Newton;\n' ...
                           'integrator LoadControl [expr 1.0/10.0];\n' ...
                           'analysis Static;\n' ...
                           'analyze 10;\n' ...
                           'wipeAnalysis'];
            
        end
        
    end
    
end