classdef damping1 < OpenSees
   
    properties
       
        format = '% 0.7f';
        
        zeta = [];  % damping coefficient
        
    end
    
    methods
       
        function obj = damping1(zeta)
            
            % store variables
            obj.zeta = zeta;
            
            % run eigen analysis
            obj.cmdLine = ['set nEigenI 1;\n' ...
                           'set nEigenJ 2;\n' ...
                           'set lambdaN [eigen $nEigenJ];\n' ...
                           'set lambdaI [lindex $lambdaN [expr 0]];\n' ...
                           'set lambdaJ [lindex $lambdaN [expr $nEigenJ-1]];\n' ...
                           'set w1 [expr pow($lambdaI, 0.5)];\n' ...
                           'set w2 [expr pow($lambdaJ, 0.5)];\n' ...
                           'set T1 [expr 2.0*' num2str(pi,obj.format) '/$w1];\n' ...
                           'set T2 [expr 2.0*' num2str(pi,obj.format) '/$w2];\n' ...
                           'puts "T1 = $T1 s";\n' ...
                           'puts "T2 = $T2 s";\n' ...
                           'set zeta ' num2str(obj.zeta,obj.format) ';\n' ...
                           'set a0 [expr $zeta*2.0*$w1*$w2/($w1 + $w2)];\n' ...
                           'set a1 [expr $zeta*2.0/($w1 + $w2)];\n' ...
                           'rayleigh $a0 0.0 0.0 0.0'];
                       
        end
        
    end
    
end